# Generated by Django 4.0.4 on 2022-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened', models.CharField(max_length=300)),
                ('original', models.CharField(max_length=1000)),
            ],
        ),
    ]
